# Generated by Django 5.2.8 on 2026-01-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_cols_hall_rows_alter_hall_capacity_and_more'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats_in_hall', to='halls.hall'),
        ),
    ]
