# Generated by Django 5.2.11 on 2026-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_alter_seat_hall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ('hall__name', 'row', 'number')},
        ),
        migrations.AddField(
            model_name='seat',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('VIP', 'VIP')], default='REG', max_length=3),
        ),
    ]
