# Generated by Django 5.2.11 on 2026-02-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', through='bookings.BookingSeat', to='seats.seat'),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='seats.seat'),
        ),
    ]
