# Generated by Django 5.2.11 on 2026-02-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_seats_alter_bookingseat_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingseat',
            options={'verbose_name': 'Забронированное место', 'verbose_name_plural': 'Забронированные места'},
        ),
    ]
