# Generated by Django 5.2.11 on 2026-03-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('NORMAL', 'Обычное')], default='NORMAL', max_length=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.hall')),
            ],
            options={
                'ordering': ('hall__name', 'row', 'number'),
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
    ]
