# Generated by Django 5.2.8 on 2026-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('DR', 'Drama'), ('AC', 'Action'), ('COM', 'Comedy'), ('HO', 'Horror'), ('SF', 'Sci-Fi')], max_length=3, null=True),
        ),
    ]
