# Generated by Django 5.2.11 on 2026-02-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rows', models.PositiveIntegerField(default=5)),
                ('cols', models.PositiveIntegerField(default=10)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('NORMAL', 'Обычное')], default='NORMAL', max_length=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.hall')),
            ],
            options={
                'ordering': ('hall__name', 'row', 'number'),
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
    ]
