# Generated by Django 5.2.8 on 2026-01-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cols',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('VIP', 'VIP'), ('NORMAL', 'Обычное')], default='NORMAL', max_length=8)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_seats', to='halls.hall')),
            ],
            options={
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
    ]
