# Generated by Django 5.2.11 on 2026-02-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_cols_hall_rows_alter_hall_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='type',
            new_name='seat_type',
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.hall'),
        ),
    ]
