# Generated by Django 5.2.11 on 2026-03-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rows', models.PositiveIntegerField(default=5)),
                ('cols', models.PositiveIntegerField(default=10)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
