# Generated by Django 5.2.11 on 2026-02-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
    ]
