# Generated by Django 5.2.11 on 2026-02-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_seats_alter_bookingseat_seat'),
        ('halls', '0002_alter_seat_unique_together_remove_seat_hall'),
        ('tickets', '0003_alter_ticket_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
