# Generated by Django 5.2.11 on 2026-02-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_seats_alter_booking_total_price_and_more'),
        ('cinema_booking_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema_booking_sessions.session'),
        ),
    ]
