# Generated by Django 5.2.11 on 2026-02-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
