# Generated by Django 5.2.11 on 2026-03-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_booking_sessions', '0001_initial'),
        ('tickets', '0003_alter_ticket_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema_booking_sessions.session'),
        ),
    ]
