# Generated by Django 5.2.11 on 2026-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_hall_movie_session_booking_seat_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='session',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='session',
            name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr/'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
