# Generated by Django 5.2.11 on 2026-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Длительность в минутах')),
                ('genre', models.CharField(blank=True, choices=[('DR', 'Drama'), ('AC', 'Action'), ('COM', 'Comedy'), ('HO', 'Horror'), ('SF', 'Sci-Fi')], max_length=3, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
